services:
  db:
    image: postgres:16
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: claria
      POSTGRES_PASSWORD: claria
      POSTGRES_DB: claria_development
    volumes:
      - postgresql_data:/var/lib/postgresql/data
volumes:
  postgresql_data: