services:
  app:
    build: .
    ports:
      - "4100:3000"
    volumes:
      - storage:/rails/storage
    env_file:
      - .env.production
  jobs:
    build: .
    command: bin/jobs
    volumes:
      - storage:/rails/storage
    env_file:
      - .env.production
    depends_on:
      - app

volumes:
  storage: