# Name of your application. Used to uniquely configure containers.
service: claria

# Name of the container image.
image: ghcr.io/iamjosejimenez/claria

servers:
  web:
    hosts:
      - clariapp.com
    options:
      memory: "600m"
      memory-swap: "900m"
  jobs:
    hosts:
      - clariapp.com
    options:
      memory: "300m"
      memory-swap: "450m"
    cmd: bin/jobs
    proxy: false

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: clariapp.com

# Credentials for your image host.
registry:
  server: ghcr.io
  username: iamjosejimenez
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
    - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
    - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
    - CLARIA_DATABASE_HOST
    - CLARIA_DATABASE_PASSWORD
    - CLARIA_DATABASE_USER
    - SECRET_KEY_BASE
    - RAILS_ENV
    - WEB_CONCURRENCY
    - PORT
    - OPENAI_API_KEY
    - SERPER_API_KEY
  clear:
    PORT: 80
    SOLID_QUEUE_IN_PUMA: false
    JOB_CONCURRENCY: 1
    WEB_CONCURRENCY: 0
    RAILS_MAX_THREADS: 3
    RAILS_ENV: production

    # Match this to any external database server to configure Active Record correctly
    # Use clariapp-db for a db accessory server on same machine via local kamal docker network.
    # DB_HOST: 192.168.0.2

    # Log everything from Rails
    # RAILS_LOG_LEVEL: debug

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"


# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "claria_storage:/rails/storage"


# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: arm64
  cache:
    type: gha

  # # Build image via remote server (useful for faster amd64 builds on arm64 computers)
  # remote: ssh://docker@docker-builder-server
  #
  # # Pass arguments and secrets to the Docker build process
  # args:
  #   RUBY_VERSION: 3.4.2
  # secrets:
  #   - GITHUB_TOKEN
  #   - RAILS_MASTER_KEY

# Use a different ssh user than root
ssh:
  user: ec2-user
  keys: [ "claria-production.pem" ]

deploy_timeout: 60

# Use accessory services (secrets come from .kamal/secrets).
# accessories:
#   db:
#     image: mysql:8.0
#     host: 192.168.0.2
#     # Change to 3306 to expose port to the world instead of just local network.
#     port: "127.0.0.1:3306:3306"
#     env:
#       clear:
#         MYSQL_ROOT_HOST: '%'
#       secret:
#         - MYSQL_ROOT_PASSWORD
#     files:
#       - config/mysql/production.cnf:/etc/mysql/my.cnf
#       - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
#     directories:
#       - data:/var/lib/mysql
#   redis:
#     image: redis:7.0
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data
